name: PigletValidation
main: co.piglet.validation.ValidationPlugin
version: 1.0

commands:
  validate:
    description: Validates the player against the database
    usage: Command syntax is /validate [code]
    permission: validation.basic
    permission-message: You don't have the validation.basic permission
